services:
  app:
    image: front-prod
    build:
      context: ./frontend/
    environment:
      - REACT_APP_BACKEND_URL=/api/
    ports:
      - 3000:80

  server:
    image: back-prod
    build:
      context: ./backend/
    environment:
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
      - NODE_ENV=production
    ports:
      - 3001:3001
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data:/data/db

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8081:80
    container_name: reverse-proxy
    depends_on:
      - app
      - server

volumes:
  mongo_data:
